### PR TITLE
test PR

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@TomasVotruba it works 🎉 🎉 🎉 for symplify repositories inside packages.

**Comment by TomasVotruba** [comment]
This actually works only for members like us. External contributions fail on missing token

**Comment by samsonasik** [comment]
Ok, let me create another user to try.

**Comment by samsonasik** [comment]
@TomasVotruba it works for normal external contributors as well, see https://github.com/symplify/static-detector/pull/3 🎉 🎉 🎉

**Pull request closed without merging**
